=== zeinebBoujmil/zeinebboujmil.github.io/portfolio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:foaf="http://xmlns.com/foaf/0.1/"
           xmlns:dc="http://purl.org/dc/elements/1.1/"
           elementFormDefault="qualified">
    
    <!-- Type personnalisé pour contenu multilingue -->
    <xs:complexType name="multilangText">
        <xs:sequence>
            <xs:element name="fr" type="xs:string" minOccurs="0"/>
            <xs:element name="en" type="xs:string" minOccurs="0"/>
            <xs:element name="zh" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Élément racine -->
    <xs:element name="portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="foaf:Person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="foaf:name" type="multilangText"/>
                            <xs:element name="foaf:title" type="multilangText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="experiences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="experience" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dc:date" type="xs:string"/>
                                        <xs:element name="employer" type="xs:string"/>
                                        <xs:element name="title" type="multilangText"/>
                                        <xs:element name="dc:description" type="multilangText"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="projects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="project" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dc:title" type="multilangText"/>
                                        <xs:element name="dc:description" type="multilangText"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="education">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="diploma" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dc:date" type="xs:string"/>
                                        <xs:element name="dc:title" type="multilangText"/>
                                        <xs:element name="dc:description" type="multilangText"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="languages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="language" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="foaf:name" type="multilangText"/>
                                        <xs:element name="level" type="multilangText"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="sections">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="experience" type="multilangText"/>
                            <xs:element name="projects" type="multilangText"/>
                            <xs:element name="education" type="multilangText"/>
                            <xs:element name="languages" type="multilangText"/>
                            <xs:element name="skills" type="multilangText"/>
                            <xs:element name="contact" type="multilangText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="contact">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="foaf:phone" type="xs:string"/>
                            <xs:element name="foaf:mbox" type="xs:string"/>
                            <xs:element name="foaf:homepage" type="xs:anyURI"/>
                            <xs:element name="foaf:based_near" type="multilangText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== zeinebBoujmil/zeinebboujmil.github.io/portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<portfolio xmlns:foaf="http://xmlns.com/foaf/0.1/"
           xmlns:dc="http://purl.org/dc/elements/1.1/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="portfolio.xsd">
    
    <foaf:Person>
        <foaf:name>
            <fr>Zeineb Boujmil</fr>
            <en>Zeineb Boujmil</en>
            <zh>张伟</zh>
        </foaf:name>
        
        <foaf:title>
            <fr>Je m’appelle Zeineb Boujmil, étudiante en deuxième année du cycle ingénieur à Sup Galilée, Université Sorbonne Paris Nord.
                Actuellement, je suis en alternance au sein de l’entreprise SFR, où je développe mes compétences en informatique et en ingénierie.</fr>
            <en>My name is Zeineb Boujmil. I am a second-year engineering student at Sup Galilée, Université Sorbonne Paris Nord.
                Currently, I am doing a work-study program at SFR, where I am developing my skills in computer science and engineering.</en>
            <zh>我叫Zeineb Boujmil，是巴黎北索邦大学 Sup Galilée 工程学院二年级的工程专业学生。
                目前，我在 SFR 公司进行交替实习，不断提升自己的计算机与工程技能。</zh>
        </foaf:title>
    </foaf:Person>
    <photo>zeineb.jpg</photo>
    <experiences>
        <experience>
            <dc:date>09/2024 - 09/2026</dc:date>
            <employer>SFR</employer>
            <title>
                <fr>Développeuse Full Stack (Alternance)</fr>
                <en>Full Stack Developer (Work-Study)</en>
                <zh>全栈开发工程师（学徒制）</zh>
            </title>
            <dc:description>
                <fr>
                    Développement d'une application interne pour une équipe de gestion des mises en production, en JavaScript, Node.js et React.js.
                </fr>
                <en>
                    Developed an internal application for a deployment management team using JavaScript, Node.js, and React.js.
                </en>
                <zh>
                    使用 JavaScript、Node.js 和 React.js 为上线管理团队开发了一个内部应用程序。
                </zh>
            </dc:description>
        </experience>
        
        <experience>
            <dc:date>02/2023 - 06/2023</dc:date>
            <employer>ADDIXO, Tunisie</employer>
            <title>
                <fr>Développeuse Full Stack</fr>
                <en>Full Stack Developer</en>
                <zh>全栈开发工程师</zh>
            </title>
            <dc:description>
                <fr>
                    Conception et développement d'une interface de gestion et de suivi des stocks, couvrant les zones, machines, états, ainsi que les matières premières, produits intermédiaires et finis, en utilisant Angular 5, Spring Boot 2.1.0 et SQL. 
                    Application de la méthodologie Agile Scrum. 
                    Écriture de tests selon l’approche TDD.
                </fr>
                <en>
                    Designed and developed a stock management and tracking interface, covering zones, machines, statuses, and raw, intermediate, and final products, using Angular 5, Spring Boot 2.1.0, and SQL. 
                    Applied the Agile Scrum methodology. 
                    Wrote tests following the TDD approach.
                </en>
                <zh>
                    使用 Angular 5、Spring Boot 2.1.0 和 SQL 设计并开发了一个库存管理和跟踪界面，涵盖区域、设备、状态以及原料、中间产品和成品。
                    应用了敏捷 Scrum 方法论。
                    根据 TDD 方法编写测试。
                </zh>
            </dc:description>
        </experience>
        
        <experience>
            <dc:date>07/2022 - 09/2022</dc:date>
            <employer>CED, Tunisie</employer>
            <title>
                <fr>Développeuse Front End</fr>
                <en>Front-End Developer</en>
                <zh>前端开发工程师</zh>
            </title>
            <dc:description>
                <fr>
                    Conception d’une interface de gestion de factures avec Angular, intégrée au back-end .NET/C# via des API existantes. 
                    Optimisation du code et mise en œuvre des bonnes pratiques.
                </fr>
                <en>
                    Designed an invoice management interface using Angular, integrated with a .NET/C# back-end through existing APIs. 
                    Optimized code and applied best practices.
                </en>
                <zh>
                    使用 Angular 设计了一个发票管理界面，并通过现有 API 集成到 .NET/C# 后端。
                    优化代码并实施开发最佳实践。
                </zh>
            </dc:description>
        </experience>
        
        
    </experiences>
    
    <projects>
        <project>
            <dc:title>
                <fr>Développement d’un site web e-commerce</fr>
                <en>Development of an e-commerce website</en>
                <zh>开发一个电子商务网站</zh>
            </dc:title>
            <dc:description>
                <fr>
                    Création d’un site de vente de solutions de construction avec deux interfaces : une pour l’administrateur, l’autre pour l’utilisateur.  
                    Environnement : PHPMyAdmin, GitHub, Visual Studio Code, XAMPP, HTML, JavaScript, Bootstrap, PHP.
                </fr>
                <en>
                    Developed a construction solutions e-commerce website with two interfaces: one for admin and one for users.  
                    Environment: PHPMyAdmin, GitHub, Visual Studio Code, XAMPP, HTML, JavaScript, Bootstrap, PHP.
                </en>
                <zh>
                    开发了一个建筑解决方案电子商务网站，包含管理员和用户两个界面。  
                    使用环境：PHPMyAdmin、GitHub、Visual Studio Code、XAMPP、HTML、JavaScript、Bootstrap、PHP。
                </zh>
            </dc:description>
        </project>
        
        <project>
            <dc:title>
                <fr>Développement d’un jeu Puissance 4</fr>
                <en>Development of a Connect 4 Game</en>
                <zh>开发一个四子棋游戏</zh>
            </dc:title>
            <dc:description>
                <fr>
                    Création d’un jeu jouable à deux joueurs ou contre une intelligence artificielle.  
                    Environnement : Visual Studio Code, C.
                </fr>
                <en>
                    Developed a game playable by two players or against an AI.  
                    Environment: Visual Studio Code, C.
                </en>
                <zh>
                    开发了一个可以双人对战或对抗 AI 的四子棋游戏。  
                    使用环境：Visual Studio Code、C。
                </zh>
            </dc:description>
        </project>
        
        <project>
            <dc:title>
                <fr>Calcul efficace de l’inverse d’une matrice</fr>
                <en>Efficient Matrix Inversion</en>
                <zh>高效矩阵求逆</zh>
            </dc:title>
            <dc:description>
                <fr>
                    Implémentation d’un algorithme de type “diviser pour régner” pour inverser une matrice réelle avec une complexité réduite.  
                    Environnement : Visual Studio Code, C.
                </fr>
                <en>
                    Implemented a “divide and conquer” algorithm for real matrix inversion with reduced complexity.  
                    Environment: Visual Studio Code, C.
                </en>
                <zh>
                    使用“分而治之”算法高效求解实数矩阵的逆。  
                    使用环境：Visual Studio Code、C。
                </zh>
            </dc:description>
        </project>
        
        <project>
            <dc:title>
                <fr>Application de gestion de bibliothèque</fr>
                <en>Library Management Application</en>
                <zh>图书馆管理应用</zh>
            </dc:title>
            <dc:description>
                <fr>
                    Développement d’une application intuitive pour la gestion des emprunts et du catalogue, avec des fonctionnalités automatisées.  
                    Environnement : Eclipse, Java 7, MySQL, XAMPP.
                </fr>
                <en>
                    Developed an intuitive app for managing book loans and catalogues, with automated features.  
                    Environment: Eclipse, Java 7, MySQL, XAMPP.
                </en>
                <zh>
                    开发了一个用于图书借阅和目录管理的直观应用程序，具备自动化功能。  
                    使用环境：Eclipse、Java 7、MySQL、XAMPP。
                </zh>
            </dc:description>
        </project>
        
        <project>
            <dc:title>
                <fr>Application mobile de quiz</fr>
                <en>Mobile Quiz Application</en>
                <zh>移动测验应用</zh>
            </dc:title>
            <dc:description>
                <fr>
                    Conception d’une application de quiz éducatif avec explication des réponses.  
                    Environnement : Visual Studio Code, Flutter.
                </fr>
                <en>
                    Designed an educational quiz app with explanations for each answer.  
                    Environment: Visual Studio Code, Flutter.
                </en>
                <zh>
                    设计了一个教育类测验应用，并为每个答案提供解释。  
                    使用环境：Visual Studio Code、Flutter。
                </zh>
            </dc:description>
        </project>
        
    </projects>
    
    <education>
        <diploma>
            <dc:date>2023 - 2026</dc:date>
            <dc:title>
                <fr>Cycle ingénieur en informatique</fr>
                <en>Computer Engineering Degree</en>
                <zh>计算机工程学位</zh>
            </dc:title>
            <dc:description>
                <fr>Études à Sup Galilée, Université Sorbonne Paris Nord, spécialité informatique.</fr>
                <en>Studies at Sup Galilée, Université Sorbonne Paris Nord, major in Computer Science.</en>
                <zh>在巴黎北索邦大学 Sup Galilée 攻读计算机专业工程学位。</zh>
            </dc:description>
        </diploma>
        <diploma>
            <dc:date>2020 - 2023</dc:date>
            <dc:title>
                <fr>Licence en science informatique (Génie logiciel et système d'information)</fr>
